f1=open("application.txt","r")
f2=open("attendance.txt","r")
data1=f1.read()
data2=f2.read()
f1.close()
f2.close()
f3=open("compain.txt","w")
f3.write(data1)
f3.write(data2)
f3.close()
print("compained sucessfully")
