f = open("attendance.txt", "r")
data = f.read()
lines = data.splitlines()
words = data.split()
characters = len(data)
print("Number of lines:", len(lines))
print("Number of words:", len(words))
print("Number of characters:", characters)
f.close()